# Generated by Django 2.2.7 on 2019-12-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designquestion',
            name='inputFile',
            field=models.FileField(default='Files/empty.json', upload_to='Files/'),
        ),
        migrations.AddField(
            model_name='designquestion',
            name='outputFile',
            field=models.FileField(default='Files/empty.json', upload_to='Files/'),
        ),
        migrations.AlterField(
            model_name='designquestion',
            name='question_language',
            field=models.CharField(choices=[('C', 'C language'), ('C++', 'C plus plus'), ('Python', 'Python'), ('Verilog', 'Verilog')], max_length=30),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='knowledge_name',
            field=models.CharField(max_length=30),
        ),
    ]
