# Generated by Django 2.2.7 on 2019-12-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0002_auto_20191219_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designquestion',
            name='example_input',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='designquestion',
            name='example_output',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='designquestion',
            name='question_analysis',
            field=models.TextField(default='no'),
        ),
        migrations.AlterField(
            model_name='selectquestion',
            name='question_analysis',
            field=models.TextField(default='no'),
        ),
    ]
