# Generated by Django 2.2.7 on 2019-12-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0003_auto_20191220_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designquestion',
            name='question_language',
            field=models.CharField(choices=[('C', 'C language'), ('C++', 'C plus plus'), ('Java', 'Java'), ('Python', 'Python'), ('Verilog', 'Verilog')], max_length=30),
        ),
    ]
