# Generated by Django 2.2.7 on 2019-12-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0004_auto_20191220_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designquestion',
            name='question_language',
            field=models.CharField(choices=[('C', 'C language'), ('C++', 'C plus plus'), ('Python', 'Python'), ('Verilog', 'Verilog')], max_length=30),
        ),
    ]
