# Generated by Django 2.2.7 on 2019-12-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0007_auto_20191221_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawquestion',
            name='question_type',
            field=models.IntegerField(choices=[('0', 'Draw Graph'), ('1', 'Fill Table')], default=0),
        ),
    ]
