# Generated by Django 2.2.7 on 2019-12-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0008_auto_20191221_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawquestion',
            name='question_image',
            field=models.ImageField(default='Files/Img/green_bg.png', upload_to='static/Tapp/images/Draw'),
        ),
    ]
