# Generated by Django 2.2.7 on 2019-12-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0010_auto_20191221_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawquestion',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Draw Graph'), (1, 'Fill Table')], default=0),
        ),
    ]
